name = "HousingLifeCycleWorkhorse"
uuid = "5512304b-eb85-4d3c-8026-77be08f85b5b"
authors = ["Eirik Eylands Brandsaas <eebrandsaas@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
